# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "https://digital-hr.github.io/site/" # the base hostname & protocol for your site
github_username: canada-ca

wet_cdts_hosturl: "https://www.canada.ca/etc/designs/canada/cdts/gcweb"
wet_cdts_version: "v4_0_32"

# Build settings
markdown: kramdown
include: [
  "en",
  "fr",
  "index.html"
]
exclude: [
  "README.md",
  "CONTRIBUTING.md",
  "LICENSE.md",
  "*.json",
  "link-check.js",
  "Gemfile",
  "Gemfile.lock"
]

plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links

defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
    values:
      type: "pages"
  - 
    scope:
      path: "en/*"
    values:
      lang: "en"
      layout: "default"
  - 
    scope:
      path: "fr/*"
    values:
      lang: "fr"
      layout: "default"
  - 
    scope:
      path: "fr/apropos.md"
    values:
      lang: "fr"
      ref: "home"
  - 
    scope:
        path: "en/about.md"
    values:
        lang: "en"
        ref: "home"
  - 
    scope:
      path: "fr/equipe.md"
    values:
      lang: "fr"
      ref: "team"
  - 
    scope:
      path: "en/team.md"
    values:
      lang: "en"
      ref: "team"
  - 
    scope:
      path: "fr/mandat.md"
    values:
      lang: "fr"
      ref: "mandate"
  - 
    scope:
        path: "en/mandate.md"
    values:
        lang: "en"
        ref: "mandate"
  - 
    scope:
      path: "fr/developpement-de-produits.md"
    values:
      lang: "fr"
      ref: "productdev"
  - 
    scope:
        path: "en/product-development.md"
    values:
        lang: "en"
        ref: "productdev"
  - 
    scope:
      path: "fr/ressources.md"
    values:
      lang: "fr"
      ref: "resources"
  - 
    scope:
        path: "en/resources.md"
    values:
        lang: "en"
        ref: "resources"
  - 
    scope:
      path: "fr/developpement-de-produits.md"
    values:
      lang: "fr"
      ref: "productdev"
  - 
    scope:
        path: "en/product-development.md"
    values:
        lang: "en"
        ref: "productdev"
  - 
    scope:
      path: "fr/role-ms.md"
    values:
      lang: "fr"
      ref: "productdev_sm"
  - 
    scope:
        path: "en/role-sm.md"
    values:
        lang: "en"
        ref: "productdev_sm"
  - 
    scope:
      path: "fr/role-rp.md"
    values:
      lang: "fr"
      ref: "productdev_po"
  - 
    scope:
        path: "en/role-po.md"
    values:
        lang: "en"
        ref: "productdev_po"
  - 
    scope:
      path: "fr/role-dev.md"
    values:
      lang: "fr"
      ref: "productdev_dev"
  - 
    scope:
        path: "en/role-dev.md"
    values:
        lang: "en"
        ref: "productdev_dev"
  - 
    scope:
      path: "fr/role-em.md"
    values:
      lang: "fr"
      ref: "productdev_sme"
  - 
    scope:
        path: "en/role-sme.md"
    values:
        lang: "en"
        ref: "productdev_sme"
  - 
    scope:
      path: "fr/role-sp.md"
    values:
      lang: "fr"
      ref: "productdev_sp"
  - 
    scope:
        path: "en/role-sp.md"
    values:
        lang: "en"
        ref: "productdev_sp"
  - 
    scope:
      path: "fr/environnements.md"
    values:
      lang: "fr"
      ref: "productdev_env"
  - 
    scope:
        path: "en/environments.md"
    values:
        lang: "en"
        ref: "productdev_env"
  - 
    scope:
      path: "fr/dette-technique.md"
    values:
      lang: "fr"
      ref: "productdev_techdebt"
  - 
    scope:
        path: "en/technical-debt.md"
    values:
        lang: "en"
        ref: "productdev_techdebt"
        
optional_front_matter:
  remove_originals: true
